name: flutter_qa_example
description: Demonstrates how to use the flutter_qa plugin.
publish_to: 'none'

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  test:

  flutter_qa:
    path: ../

flutter:

  uses-material-design: true
