jobs:
  include:
    - language: android
      sudo: false
      jdk: oraclejdk8
      cache:
        directories:
          - $HOME/.pub-cache
      os:
        - linux
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - fonts-droid
      before_install:
        - cd example
        - echo yes | sdkmanager "tools" >/dev/null
        - echo yes | sdkmanager "platform-tools" >/dev/null
        - echo yes | sdkmanager "build-tools;28.0.3" >/dev/null
        - echo yes | sdkmanager "platforms;android-26" >/dev/null
        - echo yes | sdkmanager "platforms;android-28" >/dev/null
        - echo y | sdkmanager "extras;android;m2repository" >/dev/null
        - echo y | sdkmanager "extras;google;m2repository" >/dev/null
        - sdkmanager --list
        - cd ..
      install:
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - ./flutter/bin/flutter doctor -v
        - gem install coveralls-lcov
      before_script:
        - ./flutter/bin/flutter pub get
        - cd example
        - ../flutter/bin/flutter pub run build_runner build
      script:
        - ../flutter/bin/flutter -v build apk
        - ../flutter/bin/flutter test --coverage
      after_success:
        - coveralls-lcov coverage/lcov.info
