os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - ./flutter/bin/flutter doctor -v
  - gem install coveralls-lcov
before_script:
  - ./flutter/bin/flutter pub get
  - ./flutter/bin/flutter pub run build_runner build
  - cd example
  - ../flutter/bin/flutter pub run build_runner build
script:
  - ../flutter/bin/flutter -v build apk
  - ../flutter/bin/flutter test --coverage
after\_success:
  - coveralls-lcov coverage/lcov.info
cache:
  directories:
    - $HOME/.pub-cache
