name: flutter_qa
description: Flutter Q&A widgets. Collection of widgets used for query-and-answer wizards like exams, quizes and etc.
version: 1.1.1
homepage: https://github.com/PROGrand/flutter_qa

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rect_getter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.22.0
  pedantic: ^1.11.1
  coverage: ^1.6.3

flutter:
