name: flutter_qa_example_redux
description: Demonstrates how to use the flutter_qa plugin with redux.
publish_to: 'none'

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_redux: ^0.10.0
  built_value: ^8.6.1
  built_collection: ^5.1.1

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  test:

  flutter_qa:
    path: ../

  build_runner: ^2.4.6
  built_value_generator: ^8.6.1

flutter:

  uses-material-design: true
