name: flutter_qa_example_redux
description: Demonstrates how to use the flutter_qa plugin with redux.
publish_to: 'none'

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_redux: ^0.6.0
  built_value: ^7.0.9
  built_collection: ^4.3.2

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  test:

  flutter_qa:
    path: ../

  build_runner: ^1.8.1
  built_value_generator: ^7.0.9

flutter:

  uses-material-design: true
